version: '3.8'
services:
   web:
       build: .
       ports:
           - "8000:8000"
       volumes:
           - type: bind
             source: .env
             target: /app/.env
           - type: bind
             source: root.crt
             target: /app/root.crt